from typing import Iterable, List, Optional, Protocol
from ..models import Task

class ITaskStorage(Protocol):
    def add(self, task: Task) -> None: ...
    def get(self, task_id: str) -> Optional[Task]: ...
    def list_all(self) -> List[Task]: ...
    def update(self, task: Task) -> None: ...
    def delete(self, task_id: str) -> bool: ...
    def find_by_assignee(self, assignee: str) -> List[Task]: ...

class ITaskExporter(Protocol):
    def export(self, tasks: Iterable[Task], destination: str) -> None: ...
