from typing import Protocol, List, Optional
from models import Task

class ITaskStorage(Protocol):
    """Interface for task persistence."""
    def add(self, task: Task) -> None: ...
    def get_all(self) -> List[Task]: ...
    def find_by_id(self, task_id: str) -> Optional[Task]: ...

class ITaskExporter(Protocol):
    """Interface for exporting tasks."""
    def export(self, tasks: List[Task], format: str) -> str: ...
